name: MSLands
version: ${project_version}
main: fr.iban.lands.LandsPlugin
api-version: 1.16
authors: [ Iban ]
description: Plugin de protections
depend: [ Core, packetevents ]
softdepend: [ QuickShop , HeadDatabase, Guilds, Vault ]