name: Create Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2

            - name: Build with Gradle
              run: ./gradlew build

            - name: Get version
              id: get_version
              run: echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  name: Release ${{ steps.get_version.outputs.VERSION }}
                  files: |
                      libs/*.jar
                  generate_release_notes: true